development:
  bulk_sms_username: bob
  bulk_sms_password: secret
  paypal_url: https://www.sandbox.paypal.com/cgi-bin/webscr
  paypal_account: bob@example.com

test:
  bulk_sms_username: bob
  bulk_sms_password: secret
  paypal_url: https://www.sandbox.paypal.com/cgi-bin/webscr
  paypal_account: bob@example.com
