#!/usr/bin/env ruby

RAILS_ENV = ARGV.shift || 'development'
%w(irb rubygems activeresource).each { |lib| require lib }
require File.expand_path('../../config/initializers/application.rb', __FILE__)

class Base < ActiveResource::Base
  self.site = Application.admin_api_site
  self.user = Application.admin_api_token
end

class Account < Base
end

class Account::Entry < Base
  self.prefix = '/admin/accounts/:account_id/'
end

class Subscriber < Base
end

puts "Conecting to #{Application.admin_api_site}"
IRB.start(__FILE__)
